### PR TITLE
Fixed reference pointers

### PR DESCRIPTION
**Pull request by herronjo**
I fixed the numbers for each array.

### CODE REVIEW

**Comment by savaka2** [comment]
thanks, I probably forgot that those are different when copying from scratch or appinventor or both

I will merge it when I go home

**Comment by herronjo** [comment]
Alright, thanks for the prompt response while in school.

**Comment by herronjo** [comment]
It seems the stuff in the-thing is all set to go, I think. Why not release it?

**Comment by savaka2** [comment]
there are some substring(0) which don't do anything they should be substring(1) I need to fix them

**Comment by savaka2** [comment]
also the add concatenates because +

**Comment by savaka2** [comment]
and there's weird errors I can't figure out

**Comment by herronjo** [comment]
Like what? Also, whoops, I didn't know the substrings had to be 1.

**Comment by savaka2** [comment]
idk what is causing the errors

**Comment by herronjo** [comment]
It seems like it doesn't know that the function 'go()' exists.

**Comment by herronjo** [comment]
Maybe it has something to do with there being multiple scripts?

**Pull request merged**
